(function() {
  'use strict';
  const E = window.OuroEngine, D = window.OuroData;
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const colors = ['#f8cf62','#ef9973','#aabaf1','#c19cf0','#91cddb','#edd47e','#eda575','#adc991','#e7a6c8','#b9c9d8','#85c6ac','#f5d46c','#eca791','#9ab8d0','#d1b66b','#f4c889','#e89f75','#f3ae58','#9bcc9b','#a1d0e2'];
  const shapes = {
    ball:['M32 6A26 26 0 1 1 31.99 6Z','M32 20L44 28L39 42H25L20 28Z','M32 6V20M7 25L20 28M17 53L25 42M47 53L39 42M57 25L44 28'],
    boot:['M12 12H29L32 30L45 37L58 42V51H7V41L11 31Z','M11 51V57H18M29 51V57H36M48 51V57H55','M19 24L29 22M21 30L33 27M28 36L38 32'],
    board:['M13 12H51V57H13Z','M24 8H40V18H24Z','M22 28h20M22 38h12M22 47h20'],
    crown:['M7 19L18 29L32 10L46 29L57 19L51 51H13Z','M16 43H48','M28 30L32 25L36 30L32 35Z'],
    trophy:['M18 8H46V28Q46 42 32 44Q18 42 18 28Z','M18 14H8V23Q8 32 20 33M46 14H56V23Q56 32 44 33','M32 44V53M20 56H44'],
    star:['M32 5L40 23L60 25L45 39L49 59L32 49L15 59L19 39L4 25L24 23Z','M27 30h1M37 30h1','M26 37Q32 44 38 37'],
    pack:['M14 7H50V57H14Z','M14 15H50M14 49H50','M32 22L37 29L44 31L39 37L40 44L32 40L24 44L25 37L20 31L27 29Z'],
    coin:['M32 6A26 26 0 1 1 31.99 6Z','M32 12A20 20 0 1 1 31.99 12Z','M42 23Q24 13 24 28Q24 34 35 34Q46 36 38 44Q29 50 21 42M32 17V49'],
    square:['M10 10H54V54H10Z','M10 32H54M32 10V54','M19 20h4M41 20h4M19 43h4M41 43h4'],
    shield:['M32 6L54 14V33Q52 47 32 58Q12 47 10 33V14Z','M20 30L29 39L45 23'],
    eleven:['M13 8H51V56H13Z','M13 32H51M32 23A9 9 0 1 1 31.99 23Z','M21 8V17H43V8M21 56V47H43V56'],
    flame:['M34 5Q45 21 41 28L49 20Q66 49 42 57Q16 67 10 43Q8 30 25 15L23 32Q36 24 34 5Z','M30 36Q47 51 33 54Q22 53 30 36Z'],
    target:['M32 6A26 26 0 1 1 31.99 6Z','M32 17A15 15 0 1 1 31.99 17Z','M32 32L57 7M47 7H57V17']
  };
  const gold = {id:'gold', number:0, name:'XI, lenda de ouro!', icon:'crown'};
  const hue = g => g.id === 'gold' ? '#ffd457' : colors[(g.number - 1) % colors.length];
  function seal(g, locked = false) {
    const color = locked ? '#81928b' : hue(g), ink = '#273d35', icon = shapes[g.icon];
    return `<svg class="goal-seal ${locked ? 'seal-locked' : ''}" viewBox="0 0 96 112" width="96" height="112" aria-hidden="true"><g stroke="${ink}" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"><path d="M24 66L16 106L34 98L43 110L50 70M47 70L55 110L65 98L83 106L72 66" fill="${color}"/><path d="M18 104L27 71M76 104L68 71" fill="none" stroke="#fff7"/><circle cx="48" cy="45" r="40" fill="${color}"/><circle cx="48" cy="45" r="32" fill="#fff4"/><g transform="translate(25 20) scale(.72)">${icon.map((d,i) => `<path d="${d}" fill="${i ? 'none' : color}"/>`).join('')}</g><path d="M20 25l4-4M69 67l5-5" stroke="#fff"/><path d="M31 78H65V96H31Z" fill="${ink}" stroke-width="2"/></g><text x="48" y="91" text-anchor="middle" fill="#fff4d0" font-family="Arial,sans-serif" font-weight="900" font-size="12">${g.id === 'gold' ? 'XI' : String(g.number).padStart(2, '0')}</text></svg>`;
  }
  function setup(selected, profile) {
    return `<section id="career-goal-picker" class="goal-setup"><div class="goal-heading"><div><span class="eyebrow">Um desafio com a sua cara</span><h3>Objetivos da carreira</h3></div><span class="goal-count">${selected.length}/3</span></div><p>Escolha três desafios ou jogue sem objetivos. Cada conquista rende um selo. Complete os três para ganhar o selo de ouro e criar sua lenda.</p><div class="goal-selected-slots">${selected.length ? selected.map(id => {const g=E.careerGoalDefinitions.find(g=>g.id===id);return `<span>${seal(g)}<b>${esc(g.name)}</b></span>`;}).join('') : '<span class="goal-free">Carreira livre · nenhum desafio selecionado</span>'}</div><div class="actions"><button type="button" class="btn secondary small" data-action="choose-goals">${selected.length ? 'Alterar desafios' : 'Escolher meus desafios'}</button>${selected.length ? '<button type="button" class="text-button" data-action="clear-goals">Jogar sem objetivos</button>' : ''}</div>${selected.length && selected.length !== 3 ? '<p class="goal-invalid" role="status">Complete os três objetivos ou remova todos para começar.</p>' : ''}${profile.card ? `<div class="legacy-setup-note">${window.OuroStory.avatar(profile.card.name)}<p><b>${esc(profile.card.name)} · 88 OVR</b><br>Sua lenda entra no banco do novo clube e fica sempre no elenco. Por isso, o desafio “XI, é prata” fica indisponível.</p></div>` : profile.unlocked ? '<p class="goal-profile-note">Você já liberou a criação de uma lenda. Ela continua disponível na aba Carreira.</p>' : ''}</section>`;
  }
  function picker(selected, profile) {
    return `<div class="dialog-body goals-dialog-body"><div class="dialog-top"><div><span class="eyebrow">Sua missão nas cinco temporadas</span><h2 id="dialog-title">Escolha seu trio de desafios</h2><p>Selos são permanentes nesta carreira. As escolhas ficam fixas depois de criar o clube.</p></div><button type="button" class="icon-btn" data-action="goals-done" aria-label="Voltar à criação do clube">×</button></div><div class="goal-catalog">${E.careerGoalDefinitions.map(g => {const active=selected.includes(g.id), incompatible=g.id==='silver'&&profile.card, disabled=!active&&(selected.length===3||incompatible);return `<button type="button" class="goal-option ${active?'selected':''}" data-action="toggle-goal" data-id="${g.id}" aria-pressed="${active}" ${disabled?'disabled':''}>${seal(g)}<span class="goal-option-copy"><small>${g.group}</small><strong>${esc(g.name)}</strong><span>${esc(g.description)}</span>${incompatible?'<em>Sua lenda permanente é 88 OVR.</em>':''}</span><span class="goal-check" aria-hidden="true">${active?'✓':'+'}</span></button>`;}).join('')}</div><footer class="goal-picker-footer"><p aria-live="polite"><strong>${selected.length} de 3 escolhidos</strong><span>${selected.length===0?'Sem objetivos também vale.':selected.length===3?'Trio fechado. Bora construir esse legado!':'Escolha mais '+(3-selected.length)+' para fechar seu trio.'}</span></p><div class="actions"><button type="button" class="text-button" data-action="clear-goals-modal">Limpar</button><button type="button" class="btn" data-action="goals-done" ${![0,3].includes(selected.length)?'disabled':''}>${selected.length?'Confirmar trio':'Jogar sem objetivos'}</button></div></footer></div>`;
  }
  function summary(s, compact = false) {
    const status = E.careerGoalStatus(s), finale = s.phase === 'finished';
    if (!status.goals.length) return compact ? '' : '<section class="panel career-goals goal-free-panel"><h2>Carreira livre</h2><p>Você está jogando sem objetivos de carreira. Na próxima história, escolha três desafios na criação do clube para disputar os selos.</p></section>';
    return `<section class="panel career-goals ${compact?'goals-compact':''}"><div class="goal-heading"><div><span class="eyebrow">${finale?'Os selos da sua história':'Seu trio de desafios'}</span><h2>Objetivos da carreira</h2></div><span class="goal-count">${status.completed}/3</span></div><div class="career-goal-grid">${status.goals.map(g => `<article class="career-goal ${g.earned?'earned':''}">${seal(g,!g.earned)}<div><span class="goal-status">${g.earned?'Selo conquistado':finale?'Não concluído':'Em andamento'}</span><h3>${esc(g.name)}</h3>${compact?'':`<p>${esc(g.description)}</p>`}<div class="goal-progress" role="progressbar" aria-label="${esc(g.name)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${g.earned?100:Math.round(g.ratio*100)}"><span style="width:${g.earned?100:Math.round(g.ratio*100)}%"></span></div><small>${g.earned?`Temporada ${g.earned.season} · rodada ${g.earned.round}`:esc(g.progress)}</small></div></article>`).join('')}</div>${status.gold?`<div class="gold-goal-banner">${seal(gold)}<div><span class="eyebrow">Três desafios. Um legado de ouro.</span><h3>XI, lenda de ouro!</h3><p>Seu selo especial está garantido e vai junto na imagem final.</p></div></div>`:`<p class="goal-reward-hint">${3-status.completed} conquista${3-status.completed===1?'':'s'} para o selo de ouro e a criação da sua carta permanente.</p>`}${compact?'<button class="text-button" data-action="nav" data-view="career">Ver meu legado e as regras dos desafios →</button>':''}${!compact && finale && s.careerGoals.selected.includes('textor') && E.career(s).titles>=2 && s.coins>0 ? `<div class="goal-settle"><h3>O último gesto do presidente</h3><p>As premiações deixaram moedas no caixa. Destine todo o saldo à base para encerrar com zero moedas e concluir “J. Textor”. Essa decisão é definitiva e não altera os títulos.</p><button class="btn secondary" data-action="settle-final">Destinar ${s.coins.toLocaleString('pt-BR')} moedas à base</button></div>`:''}</section>`;
  }
  function reward(profile, renderCard) {
    if (!profile.unlocked) return '';
    return `<section class="panel legacy-reward">${profile.card?renderCard(profile.card):seal(gold)}<div><span class="eyebrow">Recompensa permanente desbloqueada</span><h2>${profile.card?esc(profile.card.name):'Agora o craque é você.'}</h2><p>${profile.card?'Sua lenda está salva neste navegador e acompanha todos os novos clubes. Pode mudar de posição ou ir para o banco; vendas e eventos nunca a retiram do elenco.':'Dê nome, posição e nacionalidade à sua carta 88 OVR. Ela entra nos próximos clubes, fica sempre no elenco e não pode ser vendida. Uma carta por perfil.'}</p>${profile.card?'<p class="small muted">A recompensa vale para novas carreiras. Exporte seu progresso para levar a lenda para outro navegador.</p>':'<button class="btn" data-action="create-legend">Criar minha lenda</button>'}</div></section>`;
  }
  function editor() {
    return `<div class="dialog-body"><div class="dialog-top"><div><span class="eyebrow">Do seu jeito. Para sempre no elenco.</span><h2 id="dialog-title">Crie a sua lenda</h2><p>88 de overall, com atributos próprios para a posição escolhida. Depois de salvar, a carta fica definida.</p></div><button type="button" class="icon-btn" data-action="close" aria-label="Fechar">×</button></div><form id="legacy-form"><div class="legacy-editor"><div id="legacy-preview"></div><div class="stack"><label class="field"><span>Nome na carta</span><input name="name" value="Meu Craque" minlength="2" maxlength="22" required autocomplete="off"></label><label class="field"><span>Posição</span><select name="pos">${E.legacyPositions.map(pos=>`<option ${pos==='MEI'?'selected':''}>${pos}</option>`).join('')}</select></label><label class="field"><span>Nacionalidade</span><select name="nation">${Object.entries(D.nations).map(([id,name])=>`<option value="${id}" ${id==='BR'?'selected':''}>${name}</option>`).join('')}</select></label><p class="small muted">A lenda chegará no banco do seu próximo clube. A carreira atual continua com o elenco que você montou.</p></div></div><div class="dialog-actions"><button type="button" class="btn secondary" data-action="close">Voltar</button><button type="submit" class="btn">Salvar minha carta permanente</button></div></form></div>`;
  }
  function drawSeal(ctx, g, x, y, size, locked=false) {
    ctx.save();ctx.translate(x,y);ctx.scale(size/96,size/96);ctx.strokeStyle='#273d35';ctx.lineWidth=3.5;ctx.lineJoin='round';ctx.lineCap='round';ctx.fillStyle=locked?'#81928b':hue(g);
    const paint=d=>{const p=new Path2D(d);ctx.fill(p);ctx.stroke(p);};
    paint('M24 66L16 106L34 98L43 110L50 70M47 70L55 110L65 98L83 106L72 66');
    ctx.beginPath();ctx.arc(48,45,40,0,Math.PI*2);ctx.fill();ctx.stroke();
    ctx.fillStyle='#ffffff44';ctx.beginPath();ctx.arc(48,45,32,0,Math.PI*2);ctx.fill();ctx.stroke();
    ctx.save();ctx.translate(25,20);ctx.scale(.72,.72);ctx.fillStyle=locked?'#81928b':hue(g);shapes[g.icon].forEach((d,i)=>{const p=new Path2D(d);if(!i)ctx.fill(p);ctx.stroke(p);});ctx.restore();
    ctx.fillStyle='#273d35';ctx.fillRect(31,78,34,18);ctx.fillStyle='#fff4d0';ctx.font='900 12px Arial';ctx.textAlign='center';ctx.fillText(g.id==='gold'?'XI':String(g.number).padStart(2,'0'),48,91);ctx.restore();
  }
  function drawFinalGoals(ctx, s, y) {
    const status=E.careerGoalStatus(s), items=[...status.goals,...(status.gold?[{...gold,earned:true}]:[])];
    if(!items.length)return;
    ctx.save();ctx.textAlign='left';ctx.fillStyle='#c3e77a';ctx.font='700 22px Arial';ctx.fillText(`MEUS SELOS · ${status.completed}/3 CONQUISTADOS`,80,y);
    const width=(924-(items.length-1)*16)/items.length;
    items.forEach((g,i)=>{const x=80+i*(width+16);ctx.fillStyle=g.earned?'#f5e8bb':'#315544';ctx.beginPath();ctx.roundRect(x,y+24,width,250,16);ctx.fill();drawSeal(ctx,g,x+(width-112)/2,y+34,112,!g.earned);ctx.textAlign='center';let size=21;ctx.font=`800 ${size}px Arial`;while(ctx.measureText(g.name).width>width-20&&size>12){ctx.font=`800 ${--size}px Arial`;}ctx.fillStyle=g.earned?'#26392d':'#d2dfd1';ctx.fillText(g.name,x+width/2,y+194);ctx.font='700 16px Arial';ctx.fillText(g.id==='gold'?'TRIO COMPLETO':g.earned?'CONQUISTADO':'NÃO CONCLUÍDO',x+width/2,y+226);});
    ctx.restore();
  }
  window.OuroGoalsView={setup,picker,summary,reward,editor,seal,drawFinalGoals};
})();
